"""Generate repository-scoped Codex discovery entries without copying skill bodies."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def build_entries(root: Path, check: bool = False) -> list[str]:
    """Create/check generated pointers; refuse to overwrite unrelated files."""
    sources: list[tuple[str, Path]] = []
    seen: set[str] = set()
    for category in sorted(p for p in root.glob("[0-9][0-9]-*") if p.is_dir()):
        manifest = json.loads((category / "manifest.json").read_text(encoding="utf-8"))
        names = manifest["skills"]
        if not isinstance(names, list) or not names:
            raise ValueError(f"Invalid skills manifest: {category}")
        for name in names:
            if not isinstance(name, str) or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
                raise ValueError(f"Invalid skill name: {name!r}")
            if name in seen:
                raise ValueError(f"Duplicate skill name across manifests: {name}")
            seen.add(name)
            sources.append((name, category / name / "SKILL.md"))
    if not sources:
        raise ValueError("No category skills found")
    changed: list[str] = []
    planned: list[tuple[Path, str]] = []
    for name, source in sources:
        content = source.read_text(encoding="utf-8")
        match = re.search(r"^description: (.+)$", content, re.MULTILINE)
        if not match:
            raise ValueError(f"Missing single-line description: {source}")
        description = match.group(1)
        relative = "../../../" + source.relative_to(root).as_posix()
        marker = "<!-- Generated by scripts/build_codex_entries.py -->"
        entry = (
            f"---\nname: {name}\ndescription: {description}\n---\n\n{marker}\n\n"
            f"Leia e siga [as instruções canônicas]({relative}) antes de executar esta skill.\n"
            "Resolva os links de apoio a partir do arquivo canônico.\n"
            "Se o arquivo não estiver disponível, informe que o repositório completo é necessário.\n"
        )
        target = root / ".agents" / "skills" / name / "SKILL.md"
        existing = target.read_text(encoding="utf-8") if target.exists() else None
        if existing == entry:
            continue
        changed.append(name)
        if not check:
            if existing is not None and marker not in existing:
                raise ValueError(f"Refusing to replace non-generated entry: {target}")
            planned.append((target, entry))
    for target in (root / ".agents" / "skills").glob("*/SKILL.md"):
        if target.parent.name not in seen and "<!-- Generated by scripts/build_codex_entries.py -->" in target.read_text(encoding="utf-8"):
            raise ValueError(f"Orphaned generated entry requires review: {target}")
    # Validate the entire plan before changing any file.
    for target, entry in planned:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(entry, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="Check without writing")
    args = parser.parse_args()
    try:
        changed = build_entries(args.root.resolve(), args.check)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        parser.exit(2, f"Error: {exc}\n")
    print(f"{'Outdated' if args.check else 'Updated'} entries: {len(changed)}")
    return int(args.check and bool(changed))


if __name__ == "__main__":
    raise SystemExit(main())
